name: dummy_yaml

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  bdd_widget_test:
    path: ../
  build_runner: ^2.4.10
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  patrol: ^3.7.2
