name: bdd_widget_test
description: A BDD-style widget testing library. Generates Flutter widget tests from *.feature files.
version: 1.2.1
author: Oleksandr Leushchenko <olexa.le@gmail.com>
homepage: https://github.com/olexale/bdd_widget_test

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.0.1
  build_config: ^1.0.0
  characters: ^1.1.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.0.1
  extra_pedantic: ^1.3.0
